# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: nvidia.com/v1beta1
kind: DynamoGraphDeployment
metadata:
  name: qwen-small
spec:
  backendFramework: sglang
  components:
  - name: Epp
    type: epp
    replicas: 1
    podTemplate:
      spec:
        containers:
        - name: main
          env:
          - name: DYN_KV_CACHE_BLOCK_SIZE
            value: "16"
          - name: DYN_MODEL_NAME
            value: Qwen/Qwen3.5-27B
          envFrom:
          - secretRef:
              name: hf-token-secret
          image: nvcr.io/nvidia/ai-dynamo/dynamo-frontend:my-tag
  - name: worker
    type: decode
    replicas: 1
    sharedMemorySize: 2Gi
    frontendSidecar: sidecar-frontend
    podTemplate:
      spec:
        containers:
        - name: main
          args:
          - python3 -m dynamo.sglang --model-path $MODEL_PATH --served-model-name $SERVED_MODEL_NAME
            --tp 1 --page-size 16 --mem-fraction-static 0.90
            --dyn-tool-call-parser qwen3_coder --dyn-reasoning-parser qwen3
            --kv-events-config '{"publisher":"zmq","topic":"kv-events","endpoint":"tcp://*:5557"}'
          command:
          - /bin/sh
          - -c
          env:
          - name: SERVED_MODEL_NAME
            value: Qwen/Qwen3.5-27B
          - name: MODEL_PATH
            value: Qwen/Qwen3.5-27B
          - name: DYN_STORE_KV
            value: mem
          envFrom:
          - secretRef:
              name: hf-token-secret
          image: nvcr.io/nvidia/ai-dynamo/sglang-runtime:my-tag
          resources:
            limits:
              nvidia.com/gpu: "1"
            requests:
              nvidia.com/gpu: "1"
          workingDir: /workspace/examples/backends/sglang
        - name: sidecar-frontend
          args:
          - -m
          - dynamo.frontend
          - --router-mode
          - direct
          envFrom:
          - secretRef:
              name: hf-token-secret
          image: nvcr.io/nvidia/ai-dynamo/sglang-runtime:my-tag
